# Copyright (c) 02.10.2023 Thomas Zierer.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# Contributors:
#    Thomas Zierer - initial API and implementation and/or initial documentation

name: Java CI with Maven

on:
  workflow_dispatch:
  
jobs:
  build:

    # Tests only work on Windows 
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
      # Use system JDK. If you're still on java 8 use "BREE" and add a java 17 to your toolchain
    - name: Build with Maven
      run: mvn -B verify -Dtycho-useJDK=SYSTEM --file pom.xml
